### ISSUE TITLE
include('xxx') does not check for existence of xxx

### ISSUE THREAD

**Issue by Bascy** [23andMe/Yamale#236] opened 2024-02-16 12:57 UTC
I have noticed if I use `include('xxx')` in an any() validation, that it will not complain if the xxx does not exists at all.
Is this by design?

**Comment by nbaju1** [comment] 2024-03-12 11:35
Could you provide examples of a yaml file and a schema to better illustrate your question?

**Comment by Bascy** [comment] 2024-03-16 20:26
I've managed to recreated a simple example demonstrating the problem. It seems that the missing include is reported when other errors are present

Schema:
```
nodes: map(include('node'), key=str(), required=False)
---
node: >
  any(
  include('Node1'),
  include('Node2'), 
  )
---
Node1:
  type: str(equal='Node1')
  id1: int()
```

Succeeding yaml file:
```
nodes:
  name:
    type: node2
    id1: 123
```

Failing yaml file:
```
nodes:
  name:
    type: node2
```

Errors:
> nodes.name.id1: Required field missing
> Include 'Node2' has not been defined.

**Comment by Bascy** [comment] 2024-04-23 20:52
Any news on this issue?

**Comment by cblakkan** [comment] 2024-04-24 19:57
Not by design but does seem minor since this will correctly not error in the case that none of the files being validated ever need the undefined include. Will consult internally on fixing this and report back.

**Comment by cblakkan** [comment] 2024-04-25 13:18
I've merged a change to make this always fail when there's an undefined type. Will go out soon in the next release.

**Closed by cblakkan** 2024-04-25 13:18 UTC

**Comment by Bascy** [comment] 2024-04-25 19:11
Thanks!
